name: Playwright Tests
on:
  pull_request:
    paths:
      - "frontend/**"
      - ".github/workflows/playwright.yml"
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/playwright.yml"
jobs:
  playwright:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v4
    - name: Get npm cache directory
      id: npm-cache-dir
      shell: bash
      run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
    - name: Cache npm dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Run docker compose
      uses: hoverkraft-tech/compose-action@v2.2.0
      with:
        compose-file: "./docker-compose.yml"
    - name: Wait for backend to be ready
      run: |
        echo "Waiting for backend to be ready..."
        for i in {1..30}; do
          if curl -sSf http://localhost:8016/ > /dev/null; then
            echo "Backend is up!"; break;
          fi
          sleep 5
        done
    - name: Wait for frontend to be ready
      run: |
        echo "Waiting for frontend to be ready..."
        for i in {1..30}; do
          if curl -sSf http://localhost:8015/ > /dev/null; then
            echo "Frontend is up!"; break;
          fi
          sleep 5
        done
    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install Dependencies
      run: npm i -D
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium --no-shell
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: /**/playwright-report/
        retention-days: 1
